51858612223            - الاسم: OpenInfraQuote
  # يمكنك التثبيت على الالتزام الدقيق أو الإصدار.
  # الاستخدامات: terrateamio/openinfraquote-action@6ce7f258c71e3104b75ca438a731c4f6d45d4593
  الاستخدامات: terrateamio/openinfraquote-action@v1
  مع:
    # المسار إلى ملف خطة Terraform JSON
    مسار الخطة: # اختياري، الافتراضي هو tfplan.json
    # ما إذا كان سيتم التعليق على النتيجة في طلب السحب
    تعليق على العلاقات العامة: # اختياري، الافتراضي هو صحيح
    # رمز GitHub للتعليق على طلبات السحب
    github-token: # اختياري، الافتراضي هو ${{ github.token }}
    # منطقة اختيارية لسعر oiq
    المنطقة: # اختياري، الافتراضي هو
